# Generated by Django 4.2.7 on 2023-12-23 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MisApps', '0002_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
